#!/usr/bin/env sh
set -e

make lint || (echo "lint failed"; exit 1)
make deps || (echo "deps failed"; exit 1)

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=5cb00f0
fi


# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
