// Code generated by protoc-gen-mfp. DO NOT EDIT.
// versions:
// 	protoc-gen-mfp: v0.0.1
// 	protoc:         v3.17.2
// source: 01_intro/helloworld/helloworld.proto

package helloworld

import (
	fmt "fmt"
)

func MyHelloWorld() {
	fmt.Printf("(%s!\n)", "hello_world")
}
