//go:generate go build -o $GOBIN/protoc-gen-mfp ./plugin.go
//go:generate mkdir -p ../helloworldpb
//go:generate protoc --proto_path ../../ --mfp_out=hello=hello_world:../helloworldpb ../../01_intro/helloworld/helloworld.proto
//go:generate protoc --proto_path ../../ --mfp_out=hello=hello_world,dryrun=true:../helloworldpb ../../01_intro/helloworld/helloworld.proto
package main

import (
	"flag"
	"fmt"
	"os"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

var (
	helloF = flag.String("hello", "default_value", "output hello")
	skipF  = flag.Bool("dryrun", false, "skip actual generating")
)

func main() {
	flag.Parse()

	protogen.Options{
		ParamFunc: flag.CommandLine.Set,
	}.Run(func(p *protogen.Plugin) error {
		p.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range p.Files {
			if f.Proto != nil {
				fmt.Fprintf(os.Stderr, "protoc-gen-mfp: processing %s\n", *f.Proto.Name)
			}
			if !f.Generate {
				continue
			}

			g := p.NewGeneratedFile(string(f.GoPackageName+".pb.mfp.go"), f.GoImportPath)
			g.P("// Code generated by protoc-gen-mfp. DO NOT EDIT.")
			g.P("// versions:")
			protocVersion := "(unknown)"
			if v := p.Request.GetCompilerVersion(); v != nil {
				protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
			}
			const version = "v0.0.1"
			g.P("// \tprotoc-gen-mfp: ", version)
			g.P("// \tprotoc:         ", protocVersion)
			if f.Proto != nil && f.Proto.Name != nil {
				g.P("// source: ", *f.Proto.Name)
			}
			g.P()

			g.P("package ", f.GoPackageName)
			g.P()

			g.Import(protogen.GoImportPath("fmt"))

			g.P("func MyHelloWorld() {")
			g.P(
				protogen.GoImportPath("fmt").Ident("Printf"),
				`("(%s!\n)", "`+*helloF+`")`,
			)
			g.P("}")
			g.P()

			if *skipF {
				bb, _ := g.Content()
				fmt.Fprintf(os.Stderr, "Will generate:\n%s\n", string(bb))
				g.Skip()
			}
		}

		return nil
	})
}
